<!doctype html>
<html lang="en" class="h-100">
    <?php include("../_head.html"); ?>
    <body class="d-flex flex-column h-100">
        <?php include("../_header.html"); ?>
        <!--content-->
		<div id="content" class="container mb-5 mt-3">
			<img src="https://lincolnlutheranchoir.blob.core.windows.net/images/sing.png" class="img-fluid" style="width:100%"/>
			<h3>Echoes of the Past</h3>
			<p>The Lincoln Lutheran Choir was formed in the spring of 1978 when 70 singers from 18 Lutheran congregations decided to participate in a concert of the Concordia Singers, a liturgical choir from Concordia College, Seward, Nebraska, under the leadership of Carlos R. Messerli. The concert, which was presented at Sheridan Lutheran Church, generated enough interest among singers and listeners alike that a decision was made to organize on a more formal basis under the guidance of Dr. Messerli and a Board of Directors. Through most of its history the Choir has held weekly rehearsals at Grace Lutheran Church for about twelve weeks before presenting each of two annual concerts – one in fall and one in spring.  Each rehearsal season begins with a retreat to which former and newly interested singers are invited and at which time the concert season music is introduced by the director.  The retreat location is chosen from local metro area Lutheran churches.</p>
			<p>The Choir usually sings in the formal setting of a concert, but has also been featured in the context of an Evening Prayer service. Concerts include an opportunity for congregational singing of hymns, especially in the historic mode of alternation by stanzas. This repertoire supplements  the Choir’s regular performance of chant, Renaissance motets and masses, cantatas and other Baroque works, polychoral works, and many historic and contemporary settings of liturgical and other sacred texts.</p>
			<p>Most Lincoln concerts have been held at Grace Lutheran Church, which has generously provided the Choir with a favorable acoustic environment for the performance of choral and organ music.    The Choir often performs it’s concert at an out-of-town venue  the day before the Lincoln concert.</p>
			<strong>Choir to New York City</strong>
			<p>Distinguished Concerts International New York welcomed the Lincoln Lutheran Choir to New York City to perform in <a href="http://www.facebook.com/event.php?eid=182269648482601">“Life and Remembrance in Honor of Memorial Day”</a>, a delightful celebration of the American spirit on May 30, 2011 at Alice Tully Hall, Lincoln Center! This was an enriching experience to all participants.</p>
			
			<h5>Singers</h5>
			<p>Lincoln Lutheran Choir’s members are both professional and amateur singers from Lincoln and southeast Nebraska who share a love of singing and of performing excellent sacred choral music often born out of Lutheran traditions.  Singers are encouraged to consider singing in their own home church choir as their first priority.  LLC is a concert choir; an intergenerational group of dedicated singers joining together each season to prepare two concerts a year; one in the fall, and one in the spring.  Singers from all walks of life come together to form a cohesive group in which many life-long friendships are formed.  It is indeed impressive that so many singers will give up their Sunday afternoons to participate in rehearsals for the upcoming concert.  That enriching concert experience is one that the singers look forward to with great anticipation!  Repertoire for Lincoln Lutheran Choir is that which often cannot be performed in our own home churches because of time restraints, and it provides an opportunity to learn and perform some special masterpieces.  Members of the Lincoln Lutheran Choir love to express their Christian faith by singing!</p>
			
			<h5>Organist, David Schack</h5>
			<p>David Schack has achieved a unique relationship with Lincoln Lutheran Choir that has contributed substantially to its success. For the majority of the Choir’s concerts Schack has performed as solo organist, created and performed new works for organ and for choir and organ, accompanied the Choir, and led in worship and congregational song, often with improvised accompaniment of hymns. He has participated imaginatively in performances, but extensive contributions were made in programs dedicated to the works of Buxtehude, Bach, the hymns of Jaroslav Vajda, and for the Twentieth Anniversary Concert that focused on Luther’s hymn “Christ Jesus Lay in Death’s Strong Bands.”</p>
			<p>A native of Ft. Wayne, Indiana, David Schack attended Valparaiso University and received the M.M. degree at Indiana University. He studied organ with August Stellhorn, Philip Gehring, and Oswald Ragatz. Five different publishers have published his many choral and organ compositions and his liturgical works have found wide acclaim through appearance in three major Lutheran hymnals. He has been honored by guest appearances at several regional and national conferences of the Association of Lutheran Church Musicians. Schack is organist and choir director of First Lutheran Church in Omaha, Nebraska, and Information Systems Engineer at Mutual of Omaha.</p>
		</div>
        <?php include("../_footer.html"); ?>
    </body>
</html>